#!/usr/bin/env python3
"""Generates the app icon for every platform slot from one description.

Kept in the repo so the icon is reproducible: the SVG is the source, and every
raster below is derived from it. Run it after changing the design:

    python3 packaging/icon/build_icon.py

Design: a squircle tile carrying a waveform — five stadium bars rising from the
centre line, the same gesture as the app's own PlayingEqIcon. It says "music"
rather than "media file", and unlike a triangle built from pixel blocks it holds
its shape all the way down to a 16px tray icon, where gaps between blocks turn
into mush. The gradient is the app's brand pair: the violet the theme seeds from,
into the pink of its accent.
"""

from __future__ import annotations

import math
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
SVG = HERE / "icon.svg"

# Brand pair: the theme's seed violet through to the accent pink.
VIOLET = "#5B34E8"
MID = "#8A3FE0"
PINK = "#F0559B"

CANVAS = 1024.0
# Apple's icon grid insets the art; leaving the margin here means one source
# looks right on macOS without a second, differently padded design.
TILE = CANVAS * 0.86


def squircle(cx: float, cy: float, half: float, n: float = 4.0, steps: int = 512) -> str:
    """A superellipse path — |x|^n + |y|^n = 1, the shape the UI uses for cards.

    Sampled as a polygon rather than approximated with Béziers: at these sizes
    the renderer antialiases it smooth, and the maths stays obvious.
    """
    points = []
    for i in range(steps):
        theta = 2.0 * math.pi * i / steps
        ct, st = math.cos(theta), math.sin(theta)
        # Signed power keeps the sign of the trig term while bending the curve.
        x = math.copysign(abs(ct) ** (2.0 / n), ct)
        y = math.copysign(abs(st) ** (2.0 / n), st)
        points.append(f"{cx + x * half:.3f},{cy + y * half:.3f}")
    return "M" + "L".join(points) + "Z"


def waveform() -> list[tuple[float, float, float, float]]:
    """The mark, as (x, y, width, height) stadium bars.

    Heights are deliberately uneven and asymmetric: a symmetric profile reads as
    a decorative pattern, while an uneven one reads as sound. The tallest bar
    sits just left of centre so the shape has a focal point.
    """
    profile = [0.44, 0.78, 1.00, 0.62, 0.34]
    gap_ratio = 0.62

    mark_height = TILE * 0.62
    mark_width = TILE * 0.60

    # Solve the bar width from the total: n bars plus (n-1) gaps, each gap a
    # fixed fraction of a bar.
    count = len(profile)
    bar = mark_width / (count + (count - 1) * gap_ratio)
    gap = bar * gap_ratio
    step = bar + gap

    left = (CANVAS - mark_width) / 2
    middle = CANVAS / 2

    bars: list[tuple[float, float, float, float]] = []
    for index, scale in enumerate(profile):
        height = mark_height * scale
        # Grown from the centre line, so the mark reads as a waveform rather
        # than as a bar chart standing on a baseline.
        bars.append((left + index * step, middle - height / 2, bar, height))
    return bars


def build_svg() -> str:
    tile = squircle(CANVAS / 2, CANVAS / 2, TILE / 2)
    bars = waveform()
    # Half the bar width: a stadium cap, matching the app's slider and chips.
    radius = bars[0][2] / 2

    pixels = "\n".join(
        f'    <rect x="{x:.3f}" y="{y:.3f}" width="{w:.3f}" height="{h:.3f}" '
        f'rx="{radius:.3f}" ry="{radius:.3f}"/>'
        for x, y, w, h in bars
    )

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by packaging/icon/build_icon.py — edit that, not this. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{CANVAS:.0f}" height="{CANVAS:.0f}"
     viewBox="0 0 {CANVAS:.0f} {CANVAS:.0f}">
  <defs>
    <linearGradient id="tile" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{VIOLET}"/>
      <stop offset="0.52" stop-color="{MID}"/>
      <stop offset="1" stop-color="{PINK}"/>
    </linearGradient>
    <!-- A faint top-left sheen, so the tile reads as a surface rather than a
         flat swatch. Kept subtle enough to survive downscaling to 16px. -->
    <linearGradient id="sheen" x1="0" y1="0" x2="0.35" y2="1">
      <stop offset="0" stop-color="#FFFFFF" stop-opacity="0.20"/>
      <stop offset="0.55" stop-color="#FFFFFF" stop-opacity="0"/>
    </linearGradient>
  </defs>

  <path d="{tile}" fill="url(#tile)"/>
  <path d="{tile}" fill="url(#sheen)"/>

  <g fill="#FFFFFF">
{pixels}
  </g>
</svg>
"""


def rasterise(size: int, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "rsvg-convert",
            "--width", str(size),
            "--height", str(size),
            "--output", str(out),
            str(SVG),
        ],
        check=True,
    )


def main() -> int:
    if shutil.which("rsvg-convert") is None:
        print("rsvg-convert is required (package librsvg).", file=sys.stderr)
        return 1

    SVG.write_text(build_svg())
    print(f"wrote {SVG.relative_to(ROOT)}")

    # In-app logo (the navigation rail) and the Linux desktop-entry icon.
    rasterise(1024, ROOT / "assets/images/icon.png")
    rasterise(512, ROOT / "packaging/com.theveloper.pixelplay_desktop.png")

    # macOS wants each size as its own file, named by Contents.json.
    for size in (16, 32, 64, 128, 256, 512, 1024):
        rasterise(
            size,
            ROOT / f"macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_{size}.png",
        )

    # Windows takes a single multi-resolution .ico. Pillow builds it from the
    # largest raster, and shipping the small sizes explicitly means Explorer
    # never has to invent them.
    from PIL import Image

    master = HERE / "_master_256.png"
    rasterise(256, master)
    with Image.open(master) as image:
        image.save(
            ROOT / "windows/runner/resources/app_icon.ico",
            sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)],
        )
    master.unlink()

    print("wrote every platform slot")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
